### ISSUE TITLE
ローカル環境をHTTPSで起動したい。

### ISSUE THREAD

**Issue by rook1202** [rook1202/runteq_graduation_productio-#70]
## 解決したいこと・達成したいものについて
PWAの導入の際、ローカルでも確認できるよう自己署名証明書を使用してHTTPSで開けるようにしようと考えたのですが、うまくいきませんでした。（実際は不要でした）
サーバー起動時、Listening on ssl://0.0.0.0:3000
となってほしいのですが、どうしてもListening on http://0.0.0.0:3000
となってしまいます。

## 聞きたいこと・アドバイスが欲しいこと
実装には不要でしたが、何故うまくいかないのかはわからないままでしたので、もしよろしければ、設定が悪いのでうまくいかないのか、そもそも必要ないのでもともとできないものなのか、教えていただけると助かります。

## 実装の際に参考にした資料等
資料ではないですが実際にしたこと
証明書発行：
```shell
$ openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout localhost.key -out localhost.crt
``` 
config/puma.rb追加：
```ruby
if Rails.env.development?
  cert_path = File.expand_path('certs/localhost.crt', __dir__)
  key_path = File.expand_path('certs/localhost.key', __dir__)
    puts "Certificates found: #{cert_path}, #{key_path}"
    ssl_bind '0.0.0.0', '3000', {
      key: key_path,
      cert: cert_path
    }
end
``` 
docker-compose.yml追加：
```
volumes:
      - .:/runteq_graduation_productio-
      - bundle_data:/usr/local/bundle:cached
      - node_modules:/runteq_graduation_productio-/node_modules
      - ./config/certs:/runteq_graduation_productio-/config/certs　#追加
``` 

## 現状のコードの状態がわかるURL(プルリクエスト・リポジトリ等)
https://github.com/rook1202/runteq_graduation_productio-
現在マージ済の状態から変更したファイルは以下のファイルです。

docker-compose.yml
```
services:
  db:
    image: mysql:latest
    platform: linux/amd64
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
      
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0' -p ${PORT:-3000}"
    tty: true
    stdin_open: true
    volumes:
      - .:/runteq_graduation_productio-
      - bundle_data:/usr/local/bundle:cached
      - node_modules:/runteq_graduation_productio-/node_modules
      - ./config/certs:/runteq_graduation_productio-/config/certs　#追加
    environment:
      RAILS_ENV: development　#追加
      TZ: Asia/Tokyo
      SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - db
      - chrome
  chrome:
    image: seleniarm/standalone-chromium:121.0
    ports:
      - "4444:4444"

volumes:
  mysql_data:
  bundle_data:
  node_modules:
``` 
config/puma.rb
```

max_threads_count = ENV.fetch(
  'RAILS_MAX_THREADS', 5
)
min_threads_count = ENV.fetch('RAILS_MIN_THREADS') do
  max_threads_count
end
threads min_threads_count, max_threads_count


worker_timeout 3600 if ENV.fetch('RAILS_ENV',
                                 'development') == 'development'

# Specifies the `port` that Puma will listen on to receive requests; default is 3000.
#
# 自己署名証明書の読み込み（開発環境のみ）#今回追加部分
if Rails.env.development?
  cert_path = File.expand_path('certs/localhost.crt', __dir__)
  key_path = File.expand_path('certs/localhost.key', __dir__)
    ssl_bind '0.0.0.0', '3000', {
      key: key_path,
      cert: cert_path
    }
end

# port ENV.fetch('PORT', 3000)　#上記の追加のためコメントアウト中

# Specifies the `environment` that Puma will run in.
#
environment ENV.fetch('RAILS_ENV', 'development')

# Specifies the `pidfile` that Puma will use.
pidfile ENV.fetch('PIDFILE',
                  'tmp/pids/server.pid')

plugin :tmp_restart
``` 

## 現状のコードの状態がわかるURLのどこが関係していると考えているのか
検証結果から自己署名証明書のファイルは認識しているようなので、どこかで設定の上書きが起きているのかと考えたのですが、どこが関係しているのかわかりません。上記のファイル以外ならDockerfileも怪しいでしょうか？

## 検証した結果から分かったこと・考えたこと
```
$ docker exec -it runteq_graduation_productio--web-1 openssl x509 -in /runteq_graduation_productio-/config/certs/localhost.crt -text -noout
``` 
証明書の内容確認→エラーなし
```
$ docker exec -it runteq_graduation_productio--web-1 openssl rsa -noout -modulus -in /runteq_graduation_productio-/config/certs/localhost.key | openssl md5
$ docker exec -it runteq_graduation_productio--web-1 openssl x509 -noout -modulus -in /runteq_graduation_productio-/config/certs/localhost.crt | openssl md5
``` 
実行→証明書とキー一致
```
if Rails.env.development?
  cert_path = File.expand_path('certs/localhost.crt', __dir__)
  key_path = File.expand_path('certs/localhost.key', __dir__)
  puts "Expected cert_path: #{cert_path}"
  puts "Expected key_path: #{key_path}"
  if File.exist?(cert_path) && File.exist?(key_path)
    puts "Certificates found: #{cert_path}, #{key_path}"
    ssl_bind '0.0.0.0', '3000', {
      key: key_path,
      cert: cert_path
    }
  else
    puts "Certificate or key file is missing"
  end
end
``` 
デバッグによる確認結果→
```
web-1     | Expected cert_path: /runteq_graduation_productio-/config/certs/localhost.crt
web-1     | Expected key_path: /runteq_graduation_productio-/config/certs/localhost.key
web-1     | Certificates found: /runteq_graduation_productio-/config/certs/localhost.crt, /runteq_graduation_productio-/config/certs/localhost.key
web-1     | Puma starting in single mode...
web-1     | * Puma version: 5.6.9 (ruby 3.2.3-p157) ("Birdie's Version")
web-1     | *  Min threads: 5
web-1     | *  Max threads: 5
web-1     | *  Environment: development
web-1     | *          PID: 1
web-1     | * Listening on http://0.0.0.0:3000
``` 
ファイルが存在し、認識できていることを確認
```
$ docker exec -it runteq_graduation_productio--web-1 ls -l /runteq_graduation_productio-/config/certs
total 8
-rw-r--r-- 1 1000 1000 1456 Dec  9 09:45 localhost.crt
-rw-r--r-- 1 1000 1000 1704 Dec  9 09:42 localhost.key

$ docker exec -it runteq_graduation_productio--web-1 ps aux | grep puma
root         1  0.7  1.4 1009932 112996 pts/0  Ssl+ 17:17   0:01 puma 5.6.9 (tcp
``` 
ファイルの権限の確認→OK

PWAはセキュリティ上、HTTPS環境で動作する必要があるということなので、ローカルでも確認できるよう自己署名証明書を使用してHTTPSで開けるようにしようと考えたのですが、よくよく調べてみると、http://localhost/
でもPWAは動作可能だったようです。調べ切れておらず申し訳ありません。
ただ、何故うまくいかないのかはわからないままでしたので、もしよろしければ、設定が悪いのでうまくいかないのか、そもそも必要ないのでできないものなのか、教えていただけると助かります。失礼いたしました。
